version: '3.7'

services:
  postgres:
    container_name: codestructor_postgres
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: codestructordb
      POSTGRES_PASSWORD: codestructorpass
      POSTGRES_USER: codestructoruser
    ports:
      - '5432'
    restart: unless-stopped

  pgadmin:
    container_name: codestructor_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - '5050:5050'
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:codestructoruser:codestructorpass' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
